# Generated by Django 3.2.3 on 2021-06-28 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=500, verbose_name='Task')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'usertask',
                'verbose_name_plural': 'usertasks',
            },
        ),
    ]
