# Generated by Django 3.0.7 on 2020-06-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('complete', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
