# Generated by Django 3.2.3 on 2021-06-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usertask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
